Repository boostcamp-2020/Project12-C-Slack-Web, pull requests merged in 2020-11, with the labels that each got.

#59 Feat/post message (#58)
  backend/app.js
  backend/chatServer.js
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/atom/input/Input.js
  frontend/src/atom/input/Input.stories.js
  frontend/src/index.js
  frontend/src/organism/messageEditor/MessageEditor.js
  frontend/src/page/App.css
  frontend/src/page/App.js
  frontend/src/page/App.test.js
  frontend/src/page/channel/Channel.js
  frontend/src/page/index.js
  frontend/src/page/logo.svg
Labels: 기능추가, 기반설정, 리뷰요청

#60 Feature/GitHub login
  backend/app.js
  backend/config/passport.js
  backend/controller/index.js
  backend/controller/user/index.js
  backend/controller/user/userController.js
  backend/docs/swagger.yaml
  backend/middleware/auth.js
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/hooks/Auth.js
  frontend/src/index.js
  frontend/src/page/LoginPage.js
  frontend/src/page/WorkspaceSelectPage.js
  frontend/src/util/request.js
Labels: 기능추가, 기반설정, 리뷰요청

#62 Feat/channel api
  backend/controller/channel/channel.js
  backend/controller/channel/index.js
  backend/controller/index.js
  backend/controller/search/index.js
  backend/controller/search/search.js
  backend/model/UserHistory.js
  backend/model/WorkspaceUserInfo.js
Labels: 기능추가, 리뷰요청

#63 Fix: backend package.json, frontend index.js
  backend/package-lock.json
  backend/package.json
  frontend/src/index.js
Labels: 버그수정

#66 Fix: swagger bug fix
  backend/docs/index.html
Labels: 버그수정

#67 Fix: request env, socket env
  frontend/src/page/channel/Channel.js
  frontend/src/util/request.js
Labels: 버그수정

#64 Feat/modal
  frontend/public/index.html
  frontend/src/atom/Input/index.js
  frontend/src/atom/Modal/Modal.js
  frontend/src/atom/Modal/index.js
  frontend/src/index.js
  frontend/src/organism/messageEditor/MessageEditor.js
Labels: 기능추가

#73 Docs/swagger api details
  backend/docs/swagger.yaml
Labels: 기반설정

#74 Fix: update server url
  backend/docs/swagger.yaml
Labels: 기반설정, 버그수정

#75 Feat/channel list components
  backend/controller/channel/channel.js
  frontend/package-lock.json
  frontend/src/atom/ChannelCard/ChannelCard.js
  frontend/src/atom/ChannelCard/hash.svg
  frontend/src/atom/ChannelCard/index.js
  frontend/src/atom/ChannelCard/locker.svg
  frontend/src/atom/DirectMessageCard/DirectMessageCard.js
  frontend/src/atom/DirectMessageCard/index.js
  frontend/src/atom/UserActive/UserActive.js
  frontend/src/atom/UserActive/index.js
  frontend/src/atom/UserProfileImg/UserProfileImg.js
  frontend/src/atom/UserProfileImg/index.js
  frontend/src/index.js
  frontend/src/organism/ChannelHeader/ChannelHeader.js
  frontend/src/organism/ChannelHeader/index.js
  frontend/src/organism/ChannelList/ChannelList.js
  frontend/src/organism/ChannelList/index.js
  frontend/src/organism/SectionLabel/SectionLabel.js
  frontend/src/organism/SectionLabel/index.js
  frontend/src/page/WorkspacePage.js
Labels: 기능추가, 리뷰요청

#76 login page button 추가
  frontend/.storybook/preview.js
  frontend/src/atom/GlobalStyle/GlobalStyle.js
  frontend/src/atom/GlobalStyle/index.js
  frontend/src/atom/LoginButton/LoginButton.js
  frontend/src/atom/LoginButton/LoginButton.stories.js
  frontend/src/atom/LoginButton/index.js
  frontend/src/hooks/Auth.js
  frontend/src/hooks/GithubOAuth.js
  frontend/src/index.js
  frontend/src/page/login/Login.js
  frontend/src/page/login/Login.stories.js
Labels: 기능추가, 리뷰요청, 테스트
