Repository boostcamp-2020/Project12-C-Slack-Web, pull requests merged in 2020-12, with the labels that each got.

#78 Feat/create channel modal
  .gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/atom/Button/Button.js
  frontend/src/atom/Button/Button.stories.js
  frontend/src/atom/Button/index.js
  frontend/src/atom/Icon/Icon.js
  frontend/src/atom/Icon/Icon.stories.js
  frontend/src/atom/Icon/index.js
  frontend/src/atom/Title/Title.js
  frontend/src/atom/Title/Title.stories.js
  frontend/src/atom/Title/index.js
  frontend/src/atom/index.js
  frontend/src/constant/icon.js
  frontend/src/constant/style.js
  frontend/src/organism/CreateChannelModal/CreateChannelModal.js
  frontend/src/organism/CreateChannelModal/CreateChannelModal.stories.js
  frontend/src/organism/CreateChannelModal/index.js
  frontend/src/util/index.js
Labels: 기능추가, 리뷰요청

#79 Feat/check duplicate name api (#71)
  backend/controller/channel/channel.js
  backend/controller/channel/index.js
  backend/docs/swagger.yaml
  backend/service/channel.js
  backend/service/index.js
  backend/util/index.js
Labels: 기능추가, 리뷰요청

#77 login page에 제목과 설명 추가
  frontend/src/atom/LoginButton/LoginButton.js
  frontend/src/atom/SlackIcon/SlackIcon.js
  frontend/src/atom/SlackIcon/SlackIcon.stories.js
  frontend/src/atom/SlackIcon/index.js
  frontend/src/page/login/Login.js
Labels: 기능추가

#81 github icon
  frontend/package-lock.json
  frontend/package.json
  frontend/src/constant/icon.js
  frontend/src/page/login/Login.js
Labels: 기반설정

#82 Feat/channel-header
  backend/controller/channel/channel.js
  backend/controller/channel/index.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/atom/ChannelCard/ChannelCard.js
  frontend/src/atom/ChannelCard/ChannelCard.stories.js
  frontend/src/atom/ChannelMemberThumbnail/ChannelMemberThumbnail.js
  frontend/src/atom/ChannelMemberThumbnail/index.js
  frontend/src/atom/ChannelPinBtn/ChannelPinBtn.js
  frontend/src/atom/ChannelPinBtn/index.js
  frontend/src/atom/ChannelStarBtn/ChannelStarBtn.js
  frontend/src/atom/ChannelStarBtn/ChannelStarBtn.stories.js
  frontend/src/atom/ChannelStarBtn/index.js
  frontend/src/atom/ChannelTopicBtn/ChannelTopicBtn.js
  frontend/src/atom/ChannelTopicBtn/index.js
  frontend/src/atom/DirectMessageCard/DirectMessageCard.js
  frontend/src/atom/DirectMessageCard/DirectMessageCard.stories.js
  frontend/src/atom/Icon/Icon.js
  frontend/src/atom/UserActive/UserActive.stories.js
  frontend/src/atom/UserProfileImg/UserProfileImg.stories.js
  frontend/src/constant/icon.js
  frontend/src/constant/style.js
  frontend/src/organism/ChannelHeader/ChannelHeader.js
  frontend/src/organism/ChannelList/ChannelList.js
  frontend/src/organism/SectionLabel/SectionLabel.js
  frontend/src/organism/SectionLabel/SectionLabel.stories.js
  frontend/src/page/WorkspacePage.js
Labels: 기능추가, 리뷰요청

#83 workspace api
  backend/controller/index.js
  backend/controller/workspace/index.js
  backend/controller/workspace/workspace.js
  backend/docs/swagger.yaml
  backend/middleware/auth.js
  backend/package-lock.json
  backend/package.json
  backend/service/workspace.js
  backend/util/encryption.js
Labels: 기능추가, 기반설정

#84 sign-out api
  backend/controller/user/index.js
  backend/controller/user/userController.js
  frontend/src/hooks/Auth.js
  frontend/src/hooks/GithubOAuth.js
Labels: 기능추가

#85 Refactor/backend-Channel
  backend/controller/channel/channel.js
  backend/model/ChannelConfig.js
  backend/model/Section.js
  backend/model/WorkspaceUserInfo.js
  backend/service/channel.js
Labels: 기능수정, 코드개선

#86 Feat/refactor/channel create modal (#15)
  backend/controller/channel/channel.js
  backend/controller/channel/index.js
  backend/util/index.js
  frontend/.storybook/preview.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/channel.js
  frontend/src/atom/Button/Button.js
  frontend/src/atom/Button/ToggleButton/ToggleButton.js
  frontend/src/atom/Button/ToggleButton/ToggleButton.stories.js
  frontend/src/atom/Button/ToggleButton/index.js
  frontend/src/atom/Icon/Icon.js
  frontend/src/atom/Input/Input.js
  frontend/src/atom/Input/Input.stories.js
  frontend/src/constant/style.js
  frontend/src/index.js
  frontend/src/organism/CreateChannelModal/CreateChannelModal.js
  frontend/src/organism/CreateChannelModal/CreateChannelModal.stories.js
  frontend/src/organism/ModalInputSection/ModalInputSection.js
  frontend/src/organism/ModalInputSection/ModalInputSection.stories.js
  frontend/src/organism/ModalInputSection/index.js
  frontend/src/page/channel/Channel.js
  frontend/src/store.js
Labels: 기능수정, 기능추가, 리뷰요청, 코드개선

#87 select workspace page
  frontend/src/atom/Description/Description.js
  frontend/src/atom/Description/Description.stories.js
  frontend/src/atom/Description/index.js
  frontend/src/atom/MainDescription/MainDescription.js
  frontend/src/atom/MainDescription/MainDescription.stories.js
  frontend/src/atom/MainDescription/index.js
  frontend/src/constant/icon.js
  frontend/src/index.js
  frontend/src/organism/MyWorkspace/MyWorkspace.js
  frontend/src/organism/MyWorkspace/MyWorkspace.stories.js
  frontend/src/organism/MyWorkspace/index.js
  frontend/src/organism/MyWorkspaceSection/MyWorkspaceSection.js
  frontend/src/organism/MyWorkspaceSection/MyWorkspaceSection.stories.js
  frontend/src/organism/MyWorkspaceSection/index.js
  frontend/src/organism/NewWorkspaceSection/NewWorkspaceSection.js
  frontend/src/organism/NewWorkspaceSection/NewWorkspaceSection.stories.js
  frontend/src/organism/NewWorkspaceSection/index.js
  frontend/src/page/WorkspaceSelectPage.js
  frontend/src/page/selectWorkspace/SelectWorkspace.js
  frontend/src/page/selectWorkspace/SelectWorkspace.stories.js
Labels: 기능추가, 리뷰요청

#88 Feat/create workspace page
  backend/docs/swagger.yaml
  backend/service/workspace.js
  frontend/src/atom/Description/Description.js
  frontend/src/atom/MainDescription/MainDescription.js
  frontend/src/index.js
  frontend/src/organism/CreateWorkspaceInitChannel/CreateWorkspaceInitChannel.js
  frontend/src/organism/CreateWorkspaceInitChannel/CreateWorkspaceInitChannel.stories.js
  frontend/src/organism/CreateWorkspaceInitChannel/index.js
  frontend/src/organism/CreateWorkspaceName/CreateWorkspaceName.js
  frontend/src/organism/CreateWorkspaceName/CreateWorkspaceName.stories.js
  frontend/src/organism/CreateWorkspaceName/index.js
  frontend/src/organism/MyWorkspace/MyWorkspace.js
  frontend/src/organism/MyWorkspaceSection/MyWorkspaceSection.js
  frontend/src/organism/NewWorkspaceSection/NewWorkspaceSection.js
  frontend/src/page/createWorkspace/CreateWorkspace.js
  frontend/src/page/createWorkspace/CreateWorkspace.stories.js
Labels: 기능추가

#97 backend dockerfile
  backend/Dockerfile
Labels: 기반설정

#90 Feat/get chat message api (#8)
  backend/controller/chat/chat.js
  backend/controller/chat/index.js
  backend/controller/index.js
  backend/docs/swagger.yaml
  backend/model/Chat.js
  backend/service/chat.js
  backend/util/constant.js
Labels: 기능추가, 리뷰요청

#98 Feat/chat message organism
  frontend/src/atom/ChatContent/ChatContent.js
  frontend/src/atom/ChatContent/index.js
  frontend/src/atom/UserProfileImg/UserProfileImg.js
  frontend/src/constant/style.js
  frontend/src/organism/ChatMessage/ChatMessage.js
  frontend/src/organism/ChatMessage/ChatMessage.stories.js
Labels: 기능추가, 리뷰요청

#89 Refactor/recoil
  frontend/src/api/channel.js
  frontend/src/atom/ChannelStarBtn/ChannelStarBtn.js
  frontend/src/hooks/useChannelList.js
  frontend/src/hooks/useCurrentChannelInfo.js
  frontend/src/index.js
  frontend/src/organism/ChannelHeader/ChannelHeader.js
  frontend/src/organism/ChannelList/ChannelList.js
  frontend/src/organism/CreateChannelModal/CreateChannelModal.js
  frontend/src/organism/CreateWorkspaceInitChannel/CreateWorkspaceInitChannel.js
  frontend/src/organism/MyWorkspaceSection/MyWorkspaceSection.js
  frontend/src/organism/SectionLabel/SectionLabel.js
  frontend/src/page/WorkspacePage.js
  frontend/src/store.js
  frontend/src/util/request.js
Labels: 기능수정, 기능추가, 리뷰요청, 코드개선

#99 Refactor/Search & invite user
  backend/controller/search/search.js
  backend/model/ChannelConfig.js
  backend/service/channel.js
  frontend/src/organism/InviteUserToChannelModal/InviteUserToChannelModal.js
  frontend/src/organism/InviteUserToChannelModal/index.js
  frontend/src/organism/SectionLabel/SectionLabel.stories.js
Labels: 기능수정, 기능추가, 리뷰요청, 코드개선

#100 Create default channel
  backend/service/workspace.js
  frontend/src/organism/CreateWorkspaceInitChannel/CreateWorkspaceInitChannel.js
Labels: 기능수정, 기능추가, 리뷰요청

#103 Refactor/update css style & code refactoring
  backend/model/ChannelConfig.js
  backend/model/WorkspaceUserInfo.js
  backend/service/channel.js
  frontend/src/atom/ChannelCard/ChannelCard.js
  frontend/src/atom/ChannelListHeader/ChannelListHeader.js
  frontend/src/atom/ChannelListHeader/index.js
  frontend/src/atom/ChannelMemberThumbnail/ChannelMemberThumbnail.js
  frontend/src/atom/ChannelPinBtn/ChannelPinBtn.js
  frontend/src/atom/ChannelStarBtn/ChannelStarBtn.js
  frontend/src/atom/ChannelTopicBtn/ChannelTopicBtn.js
  frontend/src/atom/DirectMessageCard/DirectMessageCard.js
  frontend/src/atom/SideMenuCard/SideMenuCard.js
  frontend/src/atom/SideMenuCard/index.js
  frontend/src/atom/UserActive/UserActive.js
  frontend/src/atom/UserProfileImg/UserProfileImg.js
  frontend/src/constant/icon.js
  frontend/src/constant/style.js
  frontend/src/hooks/useChannelList.js
  frontend/src/hooks/useCurrentChannelInfo.js
  frontend/src/index.js
  frontend/src/organism/ChannelHeader/ChannelHeader.js
  frontend/src/organism/ChannelList/ChannelList.js
  frontend/src/organism/SectionLabel/SectionLabel.js
  frontend/src/organism/SideMenuList/SideMenuList.js
  frontend/src/organism/SideMenuList/index.js
  frontend/src/page/WorkspacePage.js
  frontend/src/store.js
  frontend/src/util/dmTitleGenerator.js
  frontend/src/util/index.js
Labels: 버그수정, 코드개선

#104 Feat/refactor/client routing
  backend/controller/workspace/index.js
  backend/controller/workspace/workspace.js
  backend/service/channel.js
  backend/service/workspace.js
  frontend/src/api/channel.js
  frontend/src/api/workspace.js
  frontend/src/atom/ChannelStarBtn/ChannelStarBtn.js
  frontend/src/atom/ChannelStarBtn/ChannelStarBtn.stories.js
  frontend/src/atom/SideMenuCard/SideMenuCard.js
  frontend/src/hooks/useChannelList.js
  frontend/src/hooks/usePromise.js
  frontend/src/index.js
  frontend/src/organism/ChannelHeader/ChannelHeader.js
  frontend/src/organism/ChannelList/ChannelList.js
  frontend/src/organism/ChatRoom/ChatRoom.js
  frontend/src/organism/ChatRoom/index.js
  frontend/src/organism/CreateChannelModal/CreateChannelModal.js
  frontend/src/organism/CreateChannelModal/CreateChannelModal.stories.js
  frontend/src/organism/SectionLabel/SectionLabel.js
  frontend/src/page/WorkspacePage/WorkspacePage.js
  frontend/src/page/WorkspacePage/index.js
  frontend/src/store.js
Labels: 기능추가, 리뷰요청, 버그수정, 코드개선

#101 Workspace default channel
  backend/model/Workspace.js
  backend/service/workspace.js
  frontend/src/organism/MyWorkspaceSection/MyWorkspaceSection.js
Labels: 기능수정, 기능추가, 리뷰요청

#102 slack icon to slack img
  frontend/src/atom/SlackIcon/SlackIcon.js
  frontend/src/atom/SlackIcon/index.js
  frontend/src/atom/SlackImage/SlackImage.js
  frontend/src/atom/SlackImage/SlackImage.stories.js
  frontend/src/atom/SlackImage/index.js
  frontend/src/page/login/Login.js
Labels: 코드개선

#107 Refactor/Bug-fix& add template
  frontend/src/atom/SideMenuCard/SideMenuCard.js
  frontend/src/constant/icon.js
  frontend/src/hooks/useChannelList.js
  frontend/src/page/WorkspacePage/WorkspacePage.js
Labels: 기능수정, 버그수정

#109 Fix/add-user-profile-url
  backend/config/passport.js
  backend/model/User.js
  backend/service/workspace.js
  frontend/src/atom/ChannelStarBtn/ChannelStarBtn.js
  frontend/src/organism/InviteUserToChannelModal/InviteUserToChannelModal.js
Labels: 기능수정, 버그수정

#110 Create workspace page 이름 검증 로직 추가
  backend/controller/workspace/index.js
  backend/controller/workspace/workspace.js
  backend/docs/swagger.yaml
  backend/service/workspace.js
  frontend/src/api/createWorkspace.js
  frontend/src/constant/style.js
  frontend/src/organism/CreateWorkspaceInitChannel/CreateWorkspaceInitChannel.js
  frontend/src/organism/CreateWorkspaceName/CreateWorkspaceName.js
Labels: 기능추가

#111 Feat/send chat message (#5)
  backend/chatServer.js
  backend/service/chat.js
  frontend/src/api/chat.js
  frontend/src/organism/ChannelHeader/ChannelHeader.js
  frontend/src/organism/ChatMessage/ChatMessage.js
  frontend/src/organism/ChatMessage/index.js
  frontend/src/organism/ChatRoom/ChatRoom.js
  frontend/src/organism/messageEditor/MessageEditor.js
Labels: 기능추가

#121 Refactor/recoil update
  backend/service/channel.js
  frontend/src/atom/ChannelListHeader/ChannelListHeader.js
  frontend/src/atom/ChannelMemberThumbnail/ChannelMemberThumbnail.js
  frontend/src/atom/ChannelStarBtn/ChannelStarBtn.js
  frontend/src/hooks/useChannelList.js
  frontend/src/hooks/useCurrentChannelInfo.js
  frontend/src/organism/ChannelHeader/ChannelHeader.js
  frontend/src/organism/ChannelList/ChannelList.js
  frontend/src/organism/ChatRoom/ChatRoom.js
  frontend/src/organism/InviteUserToChannelModal/InviteUserToChannelModal.js
  frontend/src/page/WorkspacePage/WorkspacePage.js
  frontend/src/store.js
Labels: 기능수정, 버그수정, 코드개선

#122 Refactor: add workspace info result
  backend/docs/swagger.yaml
  backend/service/workspace.js
Labels: 기능수정

#123 workspace invite modal
  backend/controller/workspace/workspace.js
  backend/service/workspace.js
  frontend/src/api/workspace.js
  frontend/src/organism/InviteWorkspaceModal/InviteWorkspaceModal.js
  frontend/src/organism/InviteWorkspaceModal/InviteWorkspaceModal.stories.js
  frontend/src/organism/InviteWorkspaceModal/index.js
Labels: 기능추가, 리뷰요청

#125 Fix: objcect not added
  backend/service/workspace.js
Labels: 버그수정

#124 create workspace button 버그 수정
  frontend/src/organism/CreateWorkspaceInitChannel/CreateWorkspaceInitChannel.js
  frontend/src/organism/CreateWorkspaceName/CreateWorkspaceName.js
Labels: 기능수정

#127 Feat/FE-Reaction modal-Reaction Bar
  frontend/package-lock.json
  frontend/package.json
  frontend/src/atom/EmojiModal/EmojiModal.js
  frontend/src/atom/EmojiModal/index.js
  frontend/src/constant/icon.js
  frontend/src/constant/style.js
  frontend/src/organism/ChatMessage/ChatMessage.js
  frontend/src/organism/ReactionBar/ReactionBar.js
  frontend/src/organism/ReactionBar/index.js
Labels: 기능추가

#129 Feat/refactor/global state management (#106)
  frontend/src/api/channel.js
  frontend/src/api/chat.js
  frontend/src/atom/ChannelListHeader/ChannelListHeader.js
  frontend/src/hooks/useChannelInfo.js
  frontend/src/hooks/useChannelList.js
  frontend/src/hooks/useWorkspace.js
  frontend/src/organism/ChannelHeader/ChannelHeader.js
  frontend/src/organism/ChatRoom/ChatRoom.js
  frontend/src/organism/InviteUserToChannelModal/InviteUserToChannelModal.js
  frontend/src/page/WorkspacePage/WorkspacePage.js
  frontend/src/page/channel/Channel.js
  frontend/src/store.js
  frontend/src/util/index.js
Labels: 리뷰요청, 버그수정, 코드개선

#135 Feat/connect modal
  frontend/src/atom/Button/AddButton/AddButton.js
  frontend/src/atom/Button/AddButton/Addbutton.stories.js
  frontend/src/atom/Button/AddButton/index.js
  frontend/src/atom/Modal/Modal.js
  frontend/src/constant/icon.js
  frontend/src/organism/CreateChannelModal/CreateChannelModal.js
  frontend/src/organism/SectionLabel/SectionLabel.js
Labels: 기능추가, 리뷰요청, 버그수정

#137 Fix: invited workspace error
  backend/service/workspace.js
Labels: 버그수정

#139 Feat/connect modal
  frontend/src/atom/Modal/Modal.js
  frontend/src/organism/InviteWorkspaceModal/InviteWorkspaceModal.js
  frontend/src/organism/SectionLabel/SectionLabel.js
Labels: 버그수정

#140 Fix/create channel
  frontend/src/api/channel.js
  frontend/src/organism/CreateChannelModal/CreateChannelModal.js
Labels: 기능수정

#141 Refactor/update reviwed code
  frontend/src/organism/ActionBar/ActionBar.js
  frontend/src/organism/ActionBar/index.js
  frontend/src/organism/ChatMessage/ChatMessage.js
  frontend/src/organism/InviteUserToChannelModal/InviteUserToChannelModal.js
  frontend/src/organism/ReactionBar/index.js
Labels: 버그수정, 코드개선

#144 Feat/reaction
  backend/docs/swagger.yaml
  backend/model/Chat.js
  backend/service/reaction.js
  frontend/src/atom/AddReactionButton/AddReactionButton.js
  frontend/src/atom/AddReactionButton/index.js
  frontend/src/atom/ThreadReactionCard/ThreadReactionCard.js
  frontend/src/atom/ThreadReactionCard/index.js
  frontend/src/constant/style.js
  frontend/src/organism/ActionBar/ActionBar.js
  frontend/src/organism/ChatMessage/ChatMessage.js
  frontend/src/organism/ThreadReactionList/ThreadReactionList.js
  frontend/src/organism/ThreadReactionList/index.js
  frontend/src/util/calculateEmojiModalLocation.js
Labels: 기능수정, 기능추가, 코드개선

#145 Feat/infinite scroll (#7)
  backend/chatServer.js
  backend/model/Chat.js
  backend/service/chat.js
  frontend/src/organism/ChatMessage/ChatMessage.js
  frontend/src/organism/ChatRoom/ChatRoom.js
  frontend/src/store.js
Labels: 기능추가, 리뷰요청

#150 Feat/refactor/socket structure (#149)
  backend/chatServer.js
  frontend/src/hooks/useSocket.js
  frontend/src/organism/ChannelList/ChannelList.js
  frontend/src/organism/ChatRoom/ChatRoom.js
  frontend/src/organism/InviteUserToChannelModal/InviteUserToChannelModal.js
  frontend/src/page/WorkspacePage/WorkspacePage.js
  frontend/src/store.js
Labels: 리뷰요청, 코드개선

#154 Refactor/reaction-realtime-update
  backend/chatServer.js
  backend/service/chat.js
  backend/service/reaction.js
  frontend/src/atom/AddReactionButton/AddReactionButton.js
  frontend/src/atom/ThreadReactionCard/ThreadReactionCard.js
  frontend/src/organism/ActionBar/ActionBar.js
  frontend/src/organism/ChatMessage/ChatMessage.js
  frontend/src/organism/ChatRoom/ChatRoom.js
  frontend/src/organism/ThreadReactionList/ThreadReactionList.js
Labels: 기능수정

#155 Refactor: github profile img 없을 경우 default image url 설정
  backend/config/passport.js
Labels: 코드개선

#159 Feat/file upload
  backend/config/s3.js
  backend/controller/file/file.js
  backend/controller/file/index.js
  backend/controller/index.js
  backend/docs/swagger.yaml
  backend/model/File.js
  backend/package-lock.json
  backend/package.json
  backend/service/file.js
  frontend/src/atom/Button/Button.js
  frontend/src/atom/Button/Button.stories.js
  frontend/src/constant/icon.js
  frontend/src/organism/FilePreview/FilePreview.js
  frontend/src/organism/FilePreview/FilePreview.stories.js
  frontend/src/organism/FilePreview/index.js
  frontend/src/organism/FileUploader/FileUploader.js
  frontend/src/organism/FileUploader/FileUploader.stories.js
  frontend/src/organism/FileUploader/index.js
  frontend/src/organism/ImgPreview/ImgPreview.js
  frontend/src/organism/ImgPreview/ImgPreview.stories.js
  frontend/src/organism/ImgPreview/index.js
Labels: 기능추가

#160 Fix: channelConfig default section bug fix
  backend/service/channel.js
  backend/service/workspace.js
  frontend/src/atom/ChannelStarBtn/ChannelStarBtn.js
Labels: 버그수정

#161 v0.0.4 배포
  backend/chatServer.js
  backend/config/passport.js
  backend/config/s3.js
  backend/controller/file/file.js
  backend/controller/file/index.js
  backend/controller/index.js
  backend/docs/swagger.yaml
  backend/model/File.js
  backend/package-lock.json
  backend/package.json
  backend/service/channel.js
  backend/service/chat.js
  backend/service/file.js
  backend/service/reaction.js
  backend/service/workspace.js
  frontend/src/atom/AddReactionButton/AddReactionButton.js
  frontend/src/atom/Button/Button.js
  frontend/src/atom/Button/Button.stories.js
  frontend/src/atom/ChannelStarBtn/ChannelStarBtn.js
  frontend/src/atom/ThreadReactionCard/ThreadReactionCard.js
  frontend/src/constant/icon.js
  frontend/src/hooks/useSocket.js
  frontend/src/organism/ActionBar/ActionBar.js
  frontend/src/organism/ChannelHeader/ChannelHeader.js
  frontend/src/organism/ChannelList/ChannelList.js
  frontend/src/organism/ChatMessage/ChatMessage.js
  frontend/src/organism/ChatRoom/ChatRoom.js
  frontend/src/organism/FilePreview/FilePreview.js
  frontend/src/organism/FilePreview/FilePreview.stories.js
  frontend/src/organism/FilePreview/index.js
  frontend/src/organism/FileUploader/FileUploader.js
  frontend/src/organism/FileUploader/FileUploader.stories.js
  frontend/src/organism/FileUploader/index.js
  frontend/src/organism/ImgPreview/ImgPreview.js
  frontend/src/organism/ImgPreview/ImgPreview.stories.js
  frontend/src/organism/ImgPreview/index.js
  frontend/src/organism/InviteUserToChannelModal/InviteUserToChannelModal.js
  frontend/src/organism/ThreadReactionList/ThreadReactionList.js
  frontend/src/page/WorkspacePage/WorkspacePage.js
  frontend/src/store.js
Labels: 기능추가

#164 Feat/thread side bar
  backend/chatServer.js
  backend/model/Chat.js
  backend/service/chat.js
  frontend/src/api/chat.js
  frontend/src/container/ActionBar/ActionBar.js
  frontend/src/container/ChatMessage/ChatMessage.js
  frontend/src/container/ChatRoom/ChatRoom.js
  frontend/src/container/SideThreadBar/SideThreadBar.js
  frontend/src/container/SideThreadBar/index.js
  frontend/src/container/ThreadReactionCard/ThreadReactionCard.js
  frontend/src/index.js
  frontend/src/page/WorkspacePage/WorkspacePage.js
  frontend/src/util/index.js
Labels: 기능추가

#165 Fix: reaction realtime update bug fix
  backend/chatServer.js
Labels: 버그수정

#166 Refactor: swagger 명세 수정
  backend/docs/swagger.yaml
Labels: 기능수정, 버그수정

#167 Workspace invite not login
  backend/controller/workspace/index.js
  backend/controller/workspace/workspace.js
  backend/middleware/auth.js
  frontend/src/hooks/GithubOAuth.js
  frontend/src/index.js
  frontend/src/page/login/Login.js
Labels: 기능추가, 버그수정

#172 Feat/apply markdown (#130)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/container/ChannelHeader/ChannelHeader.js
  frontend/src/container/ChatRoom/ChatRoom.js
  frontend/src/container/MessageEditor/MessageEditor.js
  frontend/src/container/SideThreadBar/SideThreadBar.js
  frontend/src/index.js
  frontend/src/page/WorkspacePage/WorkspacePage.js
  frontend/src/presenter/ChatContent/ChatContent.js
  frontend/src/presenter/GlobalStyle/GlobalStyle.js
Labels: 기능추가, 버그수정

#169 Feat/view thread component 구현 (#132, #6)
  frontend/src/container/ChatMessage/ChatMessage.js
  frontend/src/presenter/Button/ViewThreadButton/ViewThreadButton.js
  frontend/src/presenter/Button/ViewThreadButton/ViewThreadButton.stories.js
  frontend/src/presenter/Button/ViewThreadButton/index.js
  frontend/src/util/fx.js
Labels: 기능추가, 리뷰요청

#177 Feat: add git action auto deploy script
  .github/workflows/deploy.yml
Labels: 기능추가

#171 Feat/file content
  backend/chatServer.js
  backend/controller/file/file.js
  backend/controller/file/index.js
  backend/docs/swagger.yaml
  backend/model/Chat.js
  backend/model/File.js
  backend/service/chat.js
  backend/service/file.js
  frontend/src/constant/icon.js
  frontend/src/container/ChatMessage/ChatMessage.js
  frontend/src/container/ChatRoom/ChatRoom.js
  frontend/src/container/FilePreview/FilePreview.js
  frontend/src/container/FilePreview/FilePreview.stories.js
  frontend/src/container/FileUploader/FileUploader.js
  frontend/src/container/FileUploader/FileUploader.stories.js
  frontend/src/container/ImgPreview/ImgPreview.js
  frontend/src/container/ImgPreview/ImgPreview.stories.js
  frontend/src/container/ImgPreview/index.js
  frontend/src/container/MessageEditor/MessageEditor.js
  frontend/src/container/SideThreadBar/SideThreadBar.js
  frontend/src/presenter/ChatContent/ChatContent.js
  frontend/src/util/index.js
Labels: 기능추가

#173 Feat/dm
  backend/controller/channel/channel.js
  backend/controller/channel/index.js
  backend/controller/workspace/index.js
  backend/controller/workspace/workspace.js
  backend/service/channel.js
  backend/service/workspace.js
  frontend/src/api/channel.js
  frontend/src/api/workspace.js
  frontend/src/container/Modal/InviteUserToChannelModal/InviteUserToChannelModal.js
  frontend/src/container/SectionLabel/SectionLabel.js
  frontend/src/presenter/ChannelCard/ChannelCard.js
  frontend/src/presenter/UserProfileImg/UserProfileImg.js
Labels: 기능추가

#175 Feat/browser notification
  frontend/src/container/ChatRoom/ChatRoom.js
  frontend/src/page/WorkspacePage/WorkspacePage.js
Labels: 기능추가

#176 Refactor/reaction realtime update
  backend/chatServer.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/container/ChatMessage/ChatMessage.js
  frontend/src/container/ChatRoom/ChatRoom.js
  frontend/src/container/SideThreadBar/SideThreadBar.js
  frontend/src/container/ThreadReactionList/ThreadReactionList.js
  frontend/src/presenter/EmojiModal/EmojiModal.js
  frontend/src/presenter/ThreadReactionCard/ThreadReactionCard.js
  frontend/src/presenter/ThreadReactionCard/index.js
  frontend/src/presenter/ThreadReactionList/ThreadReactionList.js
  frontend/src/util/reactionUpdate.js
Labels: 기능수정, 버그수정, 코드개선

#178 Fix/workspace page bug fix & refactoring
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/api/channel.js
  frontend/src/container/Modal/InviteWorkspaceModal/InviteWorkspaceModal.js
  frontend/src/presenter/ChatContent/ChatContent.js
  frontend/src/util/calculateTime.js
Labels: 기능수정, 버그수정

#182 Feat/channel browser modal
  backend/controller/channel/channel.js
  backend/controller/channel/index.js
  backend/docs/swagger.yaml
  backend/model/Channel.js
  backend/service/channel.js
  backend/service/workspace.js
  frontend/src/api/channel.js
  frontend/src/container/ChatRoom/ChatRoom.js
  frontend/src/container/Modal/ChannelBrowserModal/ChannelBrowserModal.js
  frontend/src/container/Modal/ChannelBrowserModal/index.js
  frontend/src/container/SectionLabel/SectionLabel.js
  frontend/src/presenter/Button/Button.js
  frontend/src/presenter/ChannelBrowserCard/ChannelBrowserCard.js
  frontend/src/presenter/ChannelBrowserCard/index.js
Labels: 기능추가

#184 Refactor: move scroll position when loading message (#183)
  frontend/src/container/ChatRoom/ChatRoom.js
  frontend/src/presenter/GlobalStyle/GlobalStyle.js
Labels: 기능수정, 코드개선

#186 file message error && style
  frontend/src/container/FilePreview/FilePreview.js
  frontend/src/container/FileUploader/FileUploader.js
  frontend/src/container/MessageEditor/MessageEditor.js
  frontend/src/presenter/ChatContent/ChatContent.js
Labels: 기능수정, 버그수정

#187 Fix Invite DM API
  backend/service/channel.js
Labels: 버그수정

#190 Refactor/Add DraggableBoundaryLine component on SideThreadBar
  frontend/src/container/ChatMessage/ChatMessage.js
  frontend/src/container/ChatRoom/ChatRoom.js
  frontend/src/container/SideThreadBar/SideThreadBar.js
  frontend/src/page/WorkspacePage/WorkspacePage.js
  frontend/src/presenter/DraggableBoundaryLine/DraggableBoundaryLine.js
  frontend/src/presenter/DraggableBoundaryLine/index.js
  frontend/src/util/draggableLine.js
Labels: 기능수정, 기능추가

#191 Feat/message file
  frontend/src/container/FilePreview/FilePreview.js
  frontend/src/container/FilePreview/FilePreview.stories.js
  frontend/src/container/FileUploader/FileUploader.js
Labels: 기능수정, 버그수정

#193 Refactor/interaction when new message
  frontend/src/constant/icon.js
  frontend/src/container/ChatRoom/ChatRoom.js
Labels: 기능수정, 기능추가

#194 Fix/ default sidebarWidth bug fix
  frontend/src/page/WorkspacePage/WorkspacePage.js
Labels: 버그수정

#195 Fix/add SideThreadBar useEffect
  frontend/src/container/SideThreadBar/SideThreadBar.js
Labels: 버그수정

#198 Feat: add logout button to WorkspacePage
  frontend/src/api/user.js
  frontend/src/container/GlobalHeader/GlobalHeader.js
  frontend/src/container/GlobalHeader/GlobalHeader.stories.js
  frontend/src/container/GlobalHeader/index.js
  frontend/src/page/WorkspacePage/WorkspacePage.js
Labels: 기능추가

#199 Feat/copy button
  frontend/package-lock.json
  frontend/package.json
  frontend/src/container/Modal/InviteWorkspaceModal/InviteWorkspaceModal.js
  frontend/src/presenter/Button/Button.js
Labels: 기능추가

#202 Refactor: remove useChannelInfo hook
  frontend/src/container/ChannelHeader/ChannelHeader.js
  frontend/src/container/ChatRoom/ChatRoom.js
  frontend/src/container/Modal/InviteUserToChannelModal/InviteUserToChannelModal.js
  frontend/src/hooks/useChannelInfo.js
  frontend/src/hooks/useSocket.js
Labels: 코드개선

#203 Refactor/set model index
  backend/model/Channel.js
  backend/model/ChannelConfig.js
  backend/model/Chat.js
  backend/model/Reaction.js
  backend/model/Workspace.js
  backend/model/WorkspaceUserInfo.js
Labels: 코드개선

#204 Fix/reaction bug 수정
  frontend/src/container/SideThreadBar/SideThreadBar.js
  frontend/src/page/WorkspacePage/WorkspacePage.js
  frontend/src/util/reactionUpdate.js
Labels: 버그수정

#205 Fix: Reaction bug fix
  frontend/src/container/ChatRoom/ChatRoom.js
Labels: 버그수정

#206 Refactor: real time update on view thread button
  backend/chatServer.js
  frontend/src/container/ChatRoom/ChatRoom.js
  frontend/src/presenter/ChannelBrowserCard/ChannelBrowserCard.js
Labels: 기능수정
